### PR TITLE
Add API for setting APZC's DPI

### PR DESCRIPTION
**Pull request by rojkov**

### CODE REVIEW

**Comment by tworaz** [comment]
LGTM

**Comment by rainemak** [comment]
LGTM

**Comment by tmeshkova** [comment]
Are you able to see any changes  on DPI change if you call it after View initialized and shown?

**Comment by tmeshkova** [comment]
In practice you should fix this by overriding GetDPI method in EmbedlitePuppetWidget class , and make this class returning value set by pref or direct API call.

**Comment by rojkov** [comment]
`mozilla::layers::APZCTreeManager::SetDPI()` is a static method that updates a static variable inside `APZCTreeManager.cpp` which is common for all screens of the device and is taken into use immediately across the whole app (not per widget).

**Comment by rojkov** [comment]
Will submit another PR

**Pull request closed without merging**
